version: '3.8'

services:
  python-service:
    build: .
    container_name: uniframe-dubbing-service
    ports:
      - "8000:8000"
    volumes:
      - ./jobs:/app/jobs
      - ./logs:/app/logs
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - S3_BUCKET=blacksmith-lab
      - AWS_REGION=eu-north-1
      - http_proxy=http://172.17.0.1:1081
      - https_proxy=http://172.17.0.1:1081
      - HTTP_PROXY=http://172.17.0.1:1081
      - HTTPS_PROXY=http://172.17.0.1:1081
    restart: always
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
