
version: '3.8'

services:
  python-service:
    build: .
    container_name: uniframe-dubbing-service
    ports:
      - "8000:8000"
    volumes:
      - ./jobs:/app/jobs
      - ./logs:/app/logs
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - S3_BUCKET=blacksmith-lab
      - AWS_REGION=eu-north-1
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
